### ISSUE TITLE
Capture and disseminate VCEP curation process reasons

### ISSUE THREAD

**Issue by wrightmw** [ClinGen/gene-and-variant-curation-tools#318]
At point of publishing, capture reasons for the curation process.

See mockup here: https://docs.google.com/presentation/d/1TvGdv4u1YM7piqA7JzkAGXPcF46_3W7ma8qduGUOlXk/edit?usp=sharing

Outstanding issues to be discussed with invested users/proxies: 
- [ ] We should add a tool tip or similar feature with expanded definitions of the reasons. Proxies need to provide language. 
- [ ] Should users be able to select multiple reasons? If not, what (and where) will selection guidance be given to interface users?
- [ ] Clearly delineate how these reasons are going to be used to calculate the Erepo variant version. 
- [ ] Clearly delineate if we need a reason for the v4 cutover (and how that's going to be handled by the Erepo variant version algorithm). 
- [ ] Add this selection as an action to the audit trail. (proxy imput not needed, technical implementation)

**Comment by cgpreston** [comment]
Follow up slides for further proxy feedback here: https://docs.google.com/presentation/d/1zFUQpywVPHJ4lEwGrwKzLMbeEjLFqlBRCaYJ7TrQ8tg/edit#slide=id.g2542a3fea59_0_0

**Comment by cgpreston** [comment]
Follow up from Tools call on 7/20: 
1. Streamline the top menu of both GCI/VCI selections to "Curation" (major update, first digit), "Recuration" (Major update, first digit), and "Administrative update" (minor update, second digit). 
2. "Gene curation express" to become a sub option of Recuration 
3. "Republish due to technical issues" to become a subselection of "Administrative update", with a 3rd digit incrementation). 

Both tool tips and a link to the SOP/selection guidance is desired to help users. 
We need to think about what's going to happen when a user selects the wrong option. 

"New Curation" is not allowed in combination with any other selections, the other selections are allowable in combinations.

**Comment by cgpreston** [comment]
@markmandell, two (hopefully small) changes have been decided based on proxy feedback: 

For both the VCI and GCI publishing modals please: 
1. Remove the field/text box currently labeled "Additional comments about classification (optional):", this is no longer needed. 
2. Rename the field/text box current labeled "Additional comments about publishing reasons (optional):"
    * new name: "Comments about publishing reasons (optional, for internal use only):"

**Comment by wrightmw** [comment]
@cgpreston 

Do we want to just rename the currently labeled "Additional comments about classification (optional)" to "Comments about publishing reasons (optional, for internal use only)"?

And then just not implement the new text box?

**Comment by cgpreston** [comment]
@wrightmw , I think it's up to @markmandell,  which is easiest to do, but yes, we just need one box. And I like your language suggestion for the box label, thanks!
