### ISSUE TITLE
Text changes in GCI

### ISSUE THREAD

**Issue by markmandell** [ClinGen/gene-and-variant-curation-tools#325]
Here is a spreadsheet for text changes in the GCI: https://docs.google.com/spreadsheets/d/1F7utEa9da7nZmCUH1osLUn2jnAvhvQPOn66o1DNWVmA/edit#gid=0

Contains the location of text in GCI, the change, and additional notes regarding the change

**Comment by liammulh** [comment]
I am not sure who to @ (@wrightmw?), but I have a question:

I noticed that in the "Curate Family Information" page, the first "Family Label" input you see (1) doesn't have the text "Note: Do not enter real names in this field.", but farther down on the page, there is a label (2) that does have the text "Note: Do not enter real names in this field." Does (1) need the "Note: Do not enter real names in this field." text as well?

EDIT: I also noticed that the "Curate Group Information" page has an input that lacks the note (3). Does (3) need the "Note: Do not enter real names in this field." text?

### (1) Doesn't have "Note: Do not enter real names in this field."

<img width="800" alt="family-no-note" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/60749003/fe38acf3-01bf-430b-a65c-5f7913181ffd">

### (2) Does have "Note: Do not enter real names in this field."

<img width="800" alt="family-yes-note" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/60749003/c957be5d-e71c-4c9c-9488-27ba292dd1fd">

### (3) Group input without "Note: Do not enter real names in this field."

<img width="800" alt="group-no-note" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/60749003/2d106b79-456a-4df0-b1f4-d736d14e7ea4">

**Comment by wrightmw** [comment]
@liammulh Good spot! Please add that Note to all the field texts indicated.

**Comment by liammulh** [comment]
@wrightmw, do you want the changes to the classification matrix done for SOP v7 and SOP v5 as well? I ask because most (all?) of the genes in my local gci-vci-aws instance use SOP v8.

**Comment by liammulh** [comment]
One of the requests is to add an asterisk to the circled label to indicate it is a required field:

<img width="600" alt="where-to-add-asterisk" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/60749003/0a39551c-20ed-411d-b8f1-2537e9e52e5e">

(This label is in the Disease(s) & Phenotype(s) section of the Curate Case Control Evidence page.)

Whether the asterisk is shown next to that label is controlled programmatically. I don't feel comfortable manually changing the flag in the code that determines whether to show the asterisk because I don't know how changing that flag would affect other parts of the code. Since this issue is for text changes, I think this request is outside the scope of this issue. If we feel it's a priority to make this change, then we should open a separate issue and link to this comment in that issue.

EDIT: Issue [here](https://github.com/ClinGen/gene-and-variant-curation-tools/issues/329).

<details>

<summary>Code</summary>

- The aforementioned label is part of the `GroupDisease` component, which gets imported and used in the `CaseControlCuration` component: https://github.com/ClinGen/gci-vci-aws/blob/10049d1af0b5883fa0dd723fcb50b3b17ff5f580/gci-vci-react/src/components/gene-central/curations/case-control/CaseControlCuration.js#L1065-L1066
- When you use the `GroupDisease` component, you are supposed to pass a boolean flag that indicates whether the disease is required. This flag is then used to determine whether to show the asterisk.

</details>

**Comment by liammulh** [comment]
Changes are in the production website.
