### ISSUE TITLE
Individual VCI dashboard behavior - June 2023

### ISSUE THREAD

**Issue by cgpreston** [ClinGen/gene-and-variant-curation-tools#327]
Noticed by a curator, and replicated by Christine, 

As an individual curator signed in as "no affiliation", the dashboard appears to be doing the following; 
1.    Not correctly displaying the status from anything other than "in progress" 
2.    Not showing the Classification (may be related to the "in progress" status)
3.    Not showing any of the met criteria 
4.    Displaying 'invalid date [time zone code]"

This is happening on both prd and test.

**Comment by cgpreston** [comment]
<img width="779" alt="Screen Shot 2023-06-27 at 10 06 24 AM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/46766411/3cb2e558-2057-469b-a7c7-1668c35cb45f">

<img width="1045" alt="Screen Shot 2023-06-27 at 10 22 16 AM" src="https://github.com/ClinGen/gene-and-variant-curation-tools/assets/46766411/4f30d85a-ee96-4ea4-8578-cbd9561bd741">

**Comment by liammulh** [comment]
I think the code that fetches the data for this table would form the following URL if a user had no affiliation:

```
/interpretations?submitted_by={auth.PK}&action=myinterpretations
```

References:

(0): https://github.com/ClinGen/gci-vci-aws/blob/42b786dc90bcdc8d0cbe6fa215477ecbb2172257/gci-vci-react/src/pages/dashboard.js#L48
(1): https://github.com/ClinGen/gci-vci-aws/blob/42b786dc90bcdc8d0cbe6fa215477ecbb2172257/gci-vci-react/src/helpers/get_interpretations.js#L26-L56

**Comment by markmandell** [comment]
@liammulh good spot! was also within `interpretation_helpers.py`, where `minProjections` was being applied to the My Affiliations table request, we had to add a check for `action` of `myinterpretations` as you pointed out and add the "full" `projections` to `get_interpretations`.

`minProjections` were being applied to the All Interpretations table because it was not loading correctly, and we removed some unnecessary fields as the front-end doesn't display as much info for All Interpretations vs. Affiliation/My Interpretations tables. Happy to elaborate further if you want!

Merged into prod 7/11/23 👍
